//add first al


alias gd="git diff"

alias gs="git status"

alias ga="git add"

alias gc="git commit"

alias gl="git log --oneline"

alias clean="find / '*.pyc' '*.swp' | xargs rm"

alias cdw="cd /home/hihimor/la/"

